package com.email.bkjkmail.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.email.bkjkmail.bean.MailAccount;
import com.email.bkjkmail.bean.MailInfo;

import com.email.bkjkmail.db.MailAccountDao;
import com.email.bkjkmail.db.MailInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mailAccountDaoConfig;
    private final DaoConfig mailInfoDaoConfig;

    private final MailAccountDao mailAccountDao;
    private final MailInfoDao mailInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mailAccountDaoConfig = daoConfigMap.get(MailAccountDao.class).clone();
        mailAccountDaoConfig.initIdentityScope(type);

        mailInfoDaoConfig = daoConfigMap.get(MailInfoDao.class).clone();
        mailInfoDaoConfig.initIdentityScope(type);

        mailAccountDao = new MailAccountDao(mailAccountDaoConfig, this);
        mailInfoDao = new MailInfoDao(mailInfoDaoConfig, this);

        registerDao(MailAccount.class, mailAccountDao);
        registerDao(MailInfo.class, mailInfoDao);
    }
    
    public void clear() {
        mailAccountDaoConfig.clearIdentityScope();
        mailInfoDaoConfig.clearIdentityScope();
    }

    public MailAccountDao getMailAccountDao() {
        return mailAccountDao;
    }

    public MailInfoDao getMailInfoDao() {
        return mailInfoDao;
    }

}
